In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('anime.csv')
df

,anime_id,name,genre,type,episodes,rating,members
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630
1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",TV,64,9.26,793665
2,28977,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.25,114262
3,9253,Steins;Gate,"Sci-Fi, Thriller",TV,24,9.17,673572
4,9969,Gintama&#039;,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.16,151266
...,...,...,...,...,...,...,...
12289,9316,Toushindai My Lover: Minami tai Mecha-Minami,Hentai,OVA,1,4.15,211
12290,5543,Under World,Hentai,OVA,1,4.28,183
12291,5621,Violence Gekiga David no Hoshi,Hentai,OVA,4,4.88,219
12292,6133,Violence Gekiga Shin David no Hoshi: Inma Dens...,Hentai,OVA,1,4.98,175
12293,26081,Yasuji no Pornorama: Yacchimae!!,Hentai,Movie,1,5.46,142

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12294 entries, 0 to 12293
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   anime_id  12294 non-null  int64
 1   name      12294 non-null  object
 2   genre     12232 non-null  object
 3   type      12269 non-null  object
 4   episodes  12294 non-null  object
 5   rating    12064 non-null  float64
 6   members   12294 non-null  int64
dtypes: float64(1), int64(2), object(4)
memory usage: 672.5+ KB

In [4]:
df.describe()

           anime_id        rating       members
count  12294.000000  12064.000000  1.229400e+04
mean   14058.221653      6.473902  1.807134e+04
std    11455.294701      1.026746  5.482068e+04
min        1.000000      1.670000  5.000000e+00
25%     3484.250000      5.880000  2.250000e+02
50%    10260.500000      6.570000  1.550000e+03
75%    24794.500000      7.180000  9.437000e+03
max    34527.000000     10.000000  1.013917e+06

In [5]:
df.isna().sum()

anime_id      0
name          0
genre        62
type         25
episodes      0
rating      230
members       0
dtype: int64

In [6]:
rating_mean = df['rating'].mean()
df['rating'] = df['rating'].fillna(rating_mean)

In [7]:
df.dropna(inplace=True)

In [8]:
df.isna().sum()

anime_id    0
name        0
genre       0
type        0
episodes    0
rating      0
members     0
dtype: int64

In [9]:
df.duplicated().sum()

0

In [10]:
df.columns

Index(['anime_id', 'name', 'genre', 'type', 'episodes', 'rating', 'members'], dtype='object')

In [11]:
# # We will use only three columns for prediction
# members,
# genre,
# rating

In [12]:
new_df = df.drop(['anime_id', 'type', 'episodes'], axis=1)

In [13]:
new_df

,name,genre,rating,members
0,Kimi no Na wa.,"Drama, Romance, School, Supernatural",9.37,200630
1,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",9.26,793665
2,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",9.25,114262
3,Steins;Gate,"Sci-Fi, Thriller",9.17,673572
4,Gintama&#039;,"Action, Comedy, Historical, Parody, Samurai, S...",9.16,151266
...,...,...,...,...
12289,Toushindai My Lover: Minami tai Mecha-Minami,Hentai,4.15,211
12290,Under World,Hentai,4.28,183
12291,Violence Gekiga David no Hoshi,Hentai,4.88,219
12292,Violence Gekiga Shin David no Hoshi: Inma Dens...,Hentai,4.98,175
12293,Yasuji no Pornorama: Yacchimae!!,Hentai,5.46,142

In [14]:
new_df['genre'][2].split(", ")

['Action', 'Comedy', 'Historical', 'Parody', 'Samurai', 'Sci-Fi', 'Shounen']

In [15]:
def convert_genre(s):
    return s.split(", ")

In [16]:
new_df['genre'] = new_df['genre'].apply(convert_genre)
new_df

,name,genre,rating,members
0,Kimi no Na wa.,"[Drama, Romance, School, Supernatural]",9.37,200630
1,Fullmetal Alchemist: Brotherhood,"[Action, Adventure, Drama, Fantasy, Magic, Mil...",9.26,793665
2,Gintama°,"[Action, Comedy, Historical, Parody, Samurai, ...",9.25,114262
3,Steins;Gate,"[Sci-Fi, Thriller]",9.17,673572
4,Gintama&#039;,"[Action, Comedy, Historical, Parody, Samurai, ...",9.16,151266
...,...,...,...,...
12289,Toushindai My Lover: Minami tai Mecha-Minami,[Hentai],4.15,211
12290,Under World,[Hentai],4.28,183
12291,Violence Gekiga David no Hoshi,[Hentai],4.88,219
12292,Violence Gekiga Shin David no Hoshi: Inma Dens...,[Hentai],4.98,175
12293,Yasuji no Pornorama: Yacchimae!!,[Hentai],5.46,142

In [17]:
new_df['genre'] = new_df['genre'].apply(lambda x:[i.replace(" ", "")for i in x])

In [18]:
new_df

,name,genre,rating,members
0,Kimi no Na wa.,"[Drama, Romance, School, Supernatural]",9.37,200630
1,Fullmetal Alchemist: Brotherhood,"[Action, Adventure, Drama, Fantasy, Magic, Mil...",9.26,793665
2,Gintama°,"[Action, Comedy, Historical, Parody, Samurai, ...",9.25,114262
3,Steins;Gate,"[Sci-Fi, Thriller]",9.17,673572
4,Gintama&#039;,"[Action, Comedy, Historical, Parody, Samurai, ...",9.16,151266
...,...,...,...,...
12289,Toushindai My Lover: Minami tai Mecha-Minami,[Hentai],4.15,211
12290,Under World,[Hentai],4.28,183
12291,Violence Gekiga David no Hoshi,[Hentai],4.88,219
12292,Violence Gekiga Shin David no Hoshi: Inma Dens...,[Hentai],4.98,175
12293,Yasuji no Pornorama: Yacchimae!!,[Hentai],5.46,142

In [19]:
o = new_df[['name', 'genre','rating', 'members']]
o.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 12210 entries, 0 to 12293
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   name     12210 non-null  object
 1   genre    12210 non-null  object
 2   rating   12210 non-null  float64
 3   members  12210 non-null  int64
dtypes: float64(1), int64(1), object(2)
memory usage: 735.0+ KB

In [20]:
o['genre'] = o['genre'].apply(lambda x:" ".join(x))

In [21]:
o['genre'] = o['genre'].apply(lambda x:x.lower())

In [22]:
o

,name,genre,rating,members
0,Kimi no Na wa.,drama romance school supernatural,9.37,200630
1,Fullmetal Alchemist: Brotherhood,action adventure drama fantasy magic military ...,9.26,793665
2,Gintama°,action comedy historical parody samurai sci-fi...,9.25,114262
3,Steins;Gate,sci-fi thriller,9.17,673572
4,Gintama&#039;,action comedy historical parody samurai sci-fi...,9.16,151266
...,...,...,...,...
12289,Toushindai My Lover: Minami tai Mecha-Minami,hentai,4.15,211
12290,Under World,hentai,4.28,183
12291,Violence Gekiga David no Hoshi,hentai,4.88,219
12292,Violence Gekiga Shin David no Hoshi: Inma Dens...,hentai,4.98,175
12293,Yasuji no Pornorama: Yacchimae!!,hentai,5.46,142

In [23]:
import nltk
from nltk.stem.porter import PorterStemmer

In [24]:
ps = PorterStemmer()
def helper(s):
    l = []
    for i in s.split():
        l.append(ps.stem(i))
    return " ".join(l)

In [25]:
o["genre"] = o["genre"].apply(helper)

In [26]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000,stop_words="english")

In [27]:
vectors = cv.fit_transform(o["genre"]).toarray()

In [28]:
k = cv.get_feature_names_out()
for i in k:
    print(i)

action
adventur
car
comedi
dementia
demon
drama
ecchi
fantasi
fi
game
harem
hentai
histor
horror
josei
kid
magic
martialart
mecha
militari
music
mysteri
parodi
polic
psycholog
romanc
samurai
school
sci
seinen
shoujo
shoujoai
shounen
shounenai
sliceoflif
space
sport
supernatur
superpow
thriller
vampir
yaoi
yuri

In [29]:
from sklearn.metrics.pairwise import cosine_similarity

In [30]:
similarity = cosine_similarity(vectors)

In [31]:
def recommend5animes(s):
    idx = o[o["name"]==s].index[0]
    l = []

    for i in range(len(similarity)):
        # Calculate weighted similarity based on members
        weighted_similarity = similarity[idx][i] * (o["members"].iloc[idx] + o["members"].iloc[i]) / 2

        l.append((weighted_similarity, o["rating"].iloc[i], i))

    l.sort(reverse=True)
    new = []

    for i,j,k in l[1:6]:
        new.append(o["name"].iloc[k])

    return new

In [32]:
df

,anime_id,name,genre,type,episodes,rating,members
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630
1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",TV,64,9.26,793665
2,28977,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.25,114262
3,9253,Steins;Gate,"Sci-Fi, Thriller",TV,24,9.17,673572
4,9969,Gintama&#039;,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.16,151266
...,...,...,...,...,...,...,...
12289,9316,Toushindai My Lover: Minami tai Mecha-Minami,Hentai,OVA,1,4.15,211
12290,5543,Under World,Hentai,OVA,1,4.28,183
12291,5621,Violence Gekiga David no Hoshi,Hentai,OVA,4,4.88,219
12292,6133,Violence Gekiga Shin David no Hoshi: Inma Dens...,Hentai,OVA,1,4.98,175
12293,26081,Yasuji no Pornorama: Yacchimae!!,Hentai,Movie,1,5.46,142

In [33]:
df['name']

0                                           Kimi no Na wa.
1                         Fullmetal Alchemist: Brotherhood
2                                                 Gintama°
3                                              Steins;Gate
4                                            Gintama&#039;
                               ...
12289         Toushindai My Lover: Minami tai Mecha-Minami
12290                                          Under World
12291                       Violence Gekiga David no Hoshi
12292    Violence Gekiga Shin David no Hoshi: Inma Dens...
12293                     Yasuji no Pornorama: Yacchimae!!
Name: name, Length: 12210, dtype: object

In [35]:
recommend5animes('Fullmetal Alchemist: Brotherhood')

['Fullmetal Alchemist',
 'Shingeki no Kyojin',
 'Fairy Tail',
 'Magi: The Labyrinth of Magic',
 'One Piece']

# Interview Question :

## 1. Can you explain the difference between user-based and item-based collaborative filtering?

#### User-Based Collaborative Filtering (UBCF)

- Focus: Finds similar users based on their historical ratings or preferences.   

- Recommendation: Recommends items that similar users have liked.   

- Challenge: Requires a large number of users with similar tastes to make accurate recommendations.
   
#### Item-Based Collaborative Filtering (IBCF)

- Focus: Finds similar items based on how users have rated them.   

- Recommendation: Recommends items that are similar to items a user has liked.   

- Challenge: Requires a large number of ratings for each item to calculate similarity.

# 2. What is collaborative filtering, and how does it work?

Collaborative Filtering

- Personalized Recommendations: Suggests items based on user preferences and behavior.

- User-Based: Finds similar users and recommends items they liked.

- Item-Based: Finds similar items and recommends items similar to the user's past preferences.

- Widely Used: In various applications like e-commerce, streaming services, and social media.

How Collaborative Filtering Works:

1. Data Collection: Collects user ratings or interactions with items (e.g., likes, purchases, clicks). 

  
2. Similarity Calculation:

- User-Based: Finds users with similar preferences by comparing their ratings or interactions. 
  
- Item-Based: Finds similar items based on how users have rated them.   

3. Prediction: Predicts a user's rating for an item by considering the ratings of similar users or items.   

4. Recommendation: Recommends items with the highest predicted ratings to the user.

Example: If a user frequently watches sci-fi movies and has rated them highly, a collaborative filtering system might recommend other sci-fi movies that similar users have enjoyed.